version: '3.5'
volumes:
  database-data:
  redis-data:
  grafana:
  influx-data:
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
  browser:
    dns:
      - 94.140.14.15
      - 94.140.15.16
    image: selenium/node-chrome-debug
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 16
      NODE_MAX_INSTANCES: 16
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "9001:5900"
    links:
      - hub
  postgres:
    image: postgres:10
    ports:
      - 19371:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /data
    volumes:
      - database-data:/data
  redis:
    image: redis:4.0.10
    ports:
      - 7779:6379
  influxdb:
    image: influxdb:1.8.6
    ports:
      - "0.0.0.0:18086:8086"
    volumes:
      - influx-data:/var/lib/influxdb
    environment: 
      INFLUXDB_REPORTING_DISABLED=false
      INFLUXDB_DB=stonks
      INFLUXDB_HTTP_AUTH_ENABLED=false
      INFLUXDB_ADMIN_USER=stonks
      INFLUXDB_ADMIN_PASSWORD=stonks
  grafana:
    image: grafana/grafana:8.0.5
    ports:
      - "127.0.0.1:4100:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana:/var/lib/grafana
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
